<Project>
  <PropertyGroup>
    <Version>0.7.2</Version>
    <Authors>Newlands Software</Authors>
    <Company>Newlands Software</Company>
    <Product>OpsForge</Product>
    <Copyright>Copyright © 2026</Copyright>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>
